### ISSUE TITLE
Estudar HTML

### ISSUE THREAD

**Issue by Tomas025** [Tomas025/PJTProcessoSoftware#4]
Para HTML, recomendo as aulas do curso em vídeo a didática dele é muito boa, ele da muitas dicas do que vocês podem ver além das aulas deles e explica algumas outras coisas que é bom vocês verem só por conhecimento geral mesmo, muito interessante, vou estar deixando o link do curso de HTML e CSS dele, pra quem quiser também vou estar deixando o link de uma pasta do meu drive que tem umas aulas da semana omnistack onde eles fazem um projeto com HTML, CSS e Js, no entanto é algo um pouco mais avançado, menos explicado e mais extenso, do que o do Gustavo Guanabara. Vou estar deixando alguns links de paginas que vocês podem recriar se quiserem treinar.

**Curso do Gustavo Guanabara**
- > https://youtube.com/playlist?list=PLHz_AreHm4dkZ9-atkcmcBaMZdmLHft8n

**Vídeos da Semana Omnistack**

- > https://drive.google.com/drive/folders/1aFivY7cT1MNmWK7aY8J8gv1R-SqNruka?usp=sharing

**Paginas para replicar**

- > https://abdul-loopstudio.netlify.app/

- > https://abdul-sunnyside-landing-page.netlify.app/

- > https://sdann26.github.io/frontend-mentor/huddle-landing-page-with-single-introductory-section-master/

- > https://abdul-intro-with-dropdown.netlify.app/

**Comment by Marih935** [comment]
comecei a estudar

**Comment by Kauanne5** [comment]
comecei a estudar

**Comment by marcelinksks** [comment]
Comecei estudar
