### ISSUE TITLE
Estudar CSS

### ISSUE THREAD

**Issue by Tomas025** [Tomas025/PJTProcessoSoftware#5]
Para CSS, as aulas que eu recomendei em HTML também incluem CSS, mas vou estar deixando os links aqui também.

**Curso do Gustavo Guanabara**
- > https://youtube.com/playlist?list=PLHz_AreHm4dkZ9-atkcmcBaMZdmLHft8n

**Vídeos da Semana Omnistack**

- > https://drive.google.com/drive/folders/1aFivY7cT1MNmWK7aY8J8gv1R-SqNruka?usp=sharing

**Paginas para replicar**

- > https://abdul-loopstudio.netlify.app/

- > https://abdul-sunnyside-landing-page.netlify.app/

- > https://sdann26.github.io/frontend-mentor/huddle-landing-page-with-single-introductory-section-master/

- > https://abdul-intro-with-dropdown.netlify.app/

**Comment by Marih935** [comment]
comecei a estudar

**Comment by Kauanne5** [comment]
comecei a estudar

**Comment by marcelinksks** [comment]
Comecei estudar
