### ISSUE TITLE
Estudar JavaScript

### ISSUE THREAD

**Issue by Tomas025** [Tomas025/PJTProcessoSoftware#6]
Para Js, recomendo um curso do Gustavo Guanabara, no curso tem atividades pra vocês fazerem e praticarem, também tem as aulas da semana omnistack que coloquei nas outras atividades, vou estar deixando os links abaixo.

**Curso do Gustavo Guanabara**

- > https://youtube.com/playlist?list=PLntvgXM11X6pi7mW0O4ZmfUI1xDSIbmTm

**Vídeos da Semana Omnistack**

- > https://drive.google.com/drive/folders/1aFivY7cT1MNmWK7aY8J8gv1R-SqNruka?usp=sharing

**Comment by Marih935** [comment]
comecei a estudar

**Comment by marcelinksks** [comment]
Comecei estudar

**Comment by Kauanne5** [comment]
Comecei a estudar
